# action.yml
name: 'Sign RPM packages'
description: 'Sign RPM packages actions'
inputs:
  gpg_name: 
    description: 'GPG name'
    required: true
    default: ''
  gpgkey_file: 
    description: 'Path to a GPG Key file'
    required: true
    default: ''
  gpgcert_file: 
    description: 'Path to a GPG Certificate file'
    required: true
    default: ''
  rpm_path: 
    description: 'Path to the RPM files'
    required: true
    default: ''
  target_path:
    description: 'Default path where the packages should be sent to'
    required: true
    default: ''
  target_folder:
    description: 'The final folder where the packages should be sent to'
    required: true
    default: ''
  tar_name:
    description: 'A name for the tar file that will contains all generated files'
    required: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'
